check_repo_dirty: false
data_path: 'data'
experiments_path: 'logs'
analytics_path: 'analytics'
web_api: ''
web_api_frequency: 60
web_api_verify_connection: true
web_api_open_browser: true
indicators:
 -
  class_name: Scalar
  is_print: True
  name: '*'